name: Deploy applications via RSync
description: Deploy a Laravel project with all files required to run a backend-only instance
author: André Paul Grandsire
inputs:
  ssh-key:
    required: true
    description: SSH Key used to authorize user at remote server
  remote-server:
    required: true
    description: Remote server to check SSH key against and allow to SSH
runs:
  using: "composite"
  steps:
    - uses: GuillaumeFalourd/setup-rsync@v1.2
      id: rsync_setup
      with: 
        ssh_key: ${{ inputs.ssh-key }}

    - name: Set up server SSH key
      shell: bash
      run: |
        mkdir ~/.ssh && touch ~/.ssh/known_hosts
        ssh-keyscan -t rsa ${{ inputs.remote-server }} >> ~/.ssh/known_hosts
        cp ${{ steps.rsync_setup.outputs.ssh_key_path }} ~/.ssh/id
